### ISSUE TITLE
Upload can write to arbitrary folders on server

### ISSUE THREAD

**Issue by mvolfik** [0d9e-tech/archiiv#1]
Get a session cookie store in a curl cookie jar, start the server listening on `localhost:3000` and send the following request

`curl -i localhost:3000/upload//tmp/test_file -b cookiejar -X POST -d blabla`

The server will happily write the content to `/tmp/test_file`

_(Edit: originally the repro used `netcat`, but actually `curl` is enough)_

**Comment by mvolfik** [comment]
The fix will probably work, but how about this:

```
def resolve(user_directory, path):
  resolved = std.fs.path.resolvePosix([user_directory, path])
  assert resolved.startsWith(user_directory)?
```

This sounds imho more bulletproof than checking first character

Also, this helper probably belongs to fs_helper mod, no?

**Comment by ProkopRandacek** [comment]
On Tue Sep 12, 2023 at 6:53 PM CEST, Matěj Volf wrote:
> ```
> def resolve(user_directory, path):
>   resolved = std.fs.path.resolvePosix([user_directory, path])
>   assert resolved.startsWith(user_directory)?
> ```

This was the original plan but the problem is that we currenly pass
around only the fd of the user dir which is somewhat annoying[1] to turn
back into a path.

We dont even have the full path stored anywhere since we just pass
around the archív root dir fd from which we obtain user dir fds by using
user's name.

[1]: you have to open(2) the path (not knowing where it really is or if
     it exist (in which case this will fail)) and then read the path
     from /proc/self/fd/XXX...
